"use strict";
process.env.NODE_ENV = 'test';
var chai = require('chai');
var chaiHttp = require('chai-http');
var spies = require('chai-spies');
var Promise = require('bluebird');
global.chai = chai;
global.expect = global.chai.expect;
global.should = global.chai.should();
global.chaiHttp = chaiHttp;
global.Promise = Promise;
console.log('promise ', global.Promise);
chai.use(chaiHttp);
chai.use(spies);
